config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  # get 'users/show'
  # get 'user/new'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/signup' => 'users#new'
  # get 'user/:id' => 'user#show'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :catelogies
  resource :microposts, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/catelogy.rb
class Catelogy < ApplicationRecord
  has_one_attached :image
end

app/controllers/catelogies_controller.rb
class CatelogiesController < ApplicationController
  def index
    @catelogies = Catelogy.paginate(page: params[:page], per_page:2).order("created_at desc")
  end

  def show
    @catelogy = Catelogy.find(params[:id])
  end

  def new
    @catelogy = Catelogy.new
  end

  def create
    @catelogy = Catelogy.new(catelogy_params)
    if @catelogy.save
      redirect_to catelogies_path
    else
      render "new"
    end
  end

  def edit
    @catelogy = Catelogy.find(params[:id])
  end

  def update
    @catelogy = Catelogy.find(params[:id])     
    if @catelogy.update(catelogy_params)
       redirect_to catelogies_path
    else
      render "edit"
    end
  end

  def destroy
    @catelogy = Catelogy.find(params[:id])
    @catelogy.destroy
    redirect_to catelogies_path
  end
  private
  def catelogy_params
    params.require(:catelogy).permit(:name, :description, :image)    
  end
end

app/helpers/catelogies_helper.rb
module CatelogiesHelper
end

app/views/catelogies/_form.html.erb
<%= form_for @catelogy do |f| %>
  <% @catelogy.errors.full_messages_for(:name).each do |msg| %>
    <%= msg %>
  <% end %> <br>
  <% @catelogy.errors.full_messages_for(:description).each do |msg| %>
    <%= msg %>
  <% end %>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/catelogies/edit.html.erb
<h1>Catelogies#edit</h1>

<%= render "form" %>

app/views/catelogies/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Stt</th>
      <th scope="col">Image</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @catelogies.each_with_index do |catelogy, index| %>
    <tr>
      <th scope="row"><%= index+1 %></th>
      <td><%= catelogy.image %></td>
      <td><%= link_to catelogy.name, catelogy %></td>
      <td><%= catelogy.description %></td>
      <td>
        <%= link_to "Edit", edit_catelogy_path(catelogy) %>
        <%= link_to "Delete", catelogy, method: :delete, data: {confirm: "are you sure?"} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Create catelogy", new_catelogy_path %>
</div>
<%= will_paginate @catelogy %>

app/views/catelogies/new.html.erb
<h1>New Article</h1>

<%= render "form" %>

app/views/catelogies/show.html.erb
<h1>Catelogies#show</h1>
<p>Find me in app/views/catelogies/show.html.erb</p>